devServiceIp: 49.232.129.253

server:
  port: 9527
  ssl:
    # enabled: true  #开启ssl验证
    enabled: false  #开启ssl验证
    key-store: classpath:keystore.p12 #证书文件位置
    key-store-password: gszero  #上面的密钥口令
    key-store-type: PKCS12   #storetype 上面的类型
    key-alias: tomcat    #tomcat上面的alias  别名

spring:
  application:
    name: blog-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.0.3:3306/blog_gateway?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: MySql@Admin123*.
  redis:
    database: 0
    host: 172.18.0.6
    port: 6379
    password: redis-960
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.0.7:8848
    gateway:
      globalcors:
        # gateway 跨域设置
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      routes:
        # 配置路由规则
        - id: blog-auth #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://blog-auth #匹配后提供服务的路由地址
          predicates:
            - Path=/auth/**         # 断言，路径相匹配的进行路由

        - id: blog-user
          uri: lb://blog-user
          predicates:
            - Path=/user/**

        - id: blog-content
          uri: lb://blog-content
          predicates:
            - Path=/content/**

        - id: blog-file
          uri: lb://blog-file
          predicates:
            - Path=/file/**

rocketmq:
  name-server: 172.18.0.8:9876 # 访问地址
  producer:
    group: blog # 必须指定group
    send-message-timeout: 5000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2

mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN

security:
  oauth2:
    resource:
      id: blog-gateway
      user-info-uri: http://172.18.0.10:9200/auth/user-me
      prefer-token-info: false