server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      globalcors:
        # gateway 跨域设置
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      routes:
        # 配置路由规则
        - id: auth-center #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://auth-center #匹配后提供服务的路由地址
          predicates:
            - Path=/auth/**         # 断言，路径相匹配的进行路由

        - id: user-center
          uri: lb://user-center
          predicates:
            - Path=/user/**

        - id: web-blog
          uri: lb://blog-content
          predicates:
            - Path=/content/**

logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN

