devServiceIp: localhost

server:
  port: 10201

spring:
  application:
    name: blog-pi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${devServiceIp}:3306/blog_pi?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root

ftp:
  basePath: D:/files
  host: ${devServiceIp}
  httpPath: ftp://${devServiceIp}
  username: demo
  password: demo
  port: 21

mqtt:
  host: tcp://192.168.0.106:1883
  username: admin
  password: public
  clientId: clientId1
  timeout: 20
  keepalive: 20

netty:
  host: 192.168.0.53
  port: 9092
  sender: SMP1