server:
  port: 9200
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    database: 0
    host: localhost
    port: 6379
    password: redis-960
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN

access_token:
  jwt-signing-key: gszero
  add-userinfo: false